name: BlogSpot Server Docker Build and Push

on:
  push:
    branches:
      - main
    paths:
      - "server/**" # Trigger only when there are changes in the 'server' directory
  workflow_dispatch:

env:
  IMAGE: blogspot-server
  REGISTRY: ghcr.io

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${REGISTRY} -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Image
        working-directory: ./server
        run: |
          docker build --build-arg JWT_SECRET="${{ secrets.JWT_SECRET }}" --build-arg DATABASE_URL="${{ secrets.DATABASE_URL }}" -t ${{ env.REGISTRY }}/${{ github.event.repository.name }}/${{ env.IMAGE }}:latest .
          docker push ${{ env.REGISTRY }}/${{ github.event.repository.name }}/${{ env.IMAGE }}:latest
